resource_types:
  - name: docker-swarm-deploy
    type: docker-image
    source:
      repository: bristechsrm/docker-swarm-deploy

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - task: build
    file: code/concourse/build.yml
  - task: create-context
    file: code/concourse/create-context.yml
  - put: image
    params:
      build: context
  - put: swarm

resources:
- name: code
  type: git
  source:
    uri: https://github.com/BristechSRM/auth.git

- name: image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: bristechsrm
    password: {{docker-hub-password}}
    repository: bristechsrm/auth

- name: swarm
  type: docker-swarm-deploy
  source:
    serviceName: auth
    executableName: Auth
    portNumber: 9003
    repository: bristechsrm/auth
    swarmMaster: {{swarmMaster}}
    network: srm-swarm
